// The medical school picker (#85): US MD and DO schools. Mentors pick
// from this list, or type their school when it isn't here (international,
// new schools). Safe to import from client and server code.
// Adding a school is just adding a line; nothing else needs changing.

export const MD_SCHOOLS = [
  "Albany Medical College",
  "Albert Einstein College of Medicine",
  "Baylor College of Medicine",
  "Boston University Chobanian & Avedisian School of Medicine",
  "Brody School of Medicine at East Carolina University",
  "California Northstate University College of Medicine",
  "California University of Science and Medicine",
  "Carle Illinois College of Medicine",
  "Case Western Reserve University School of Medicine",
  "Central Michigan University College of Medicine",
  "Charles R. Drew University of Medicine and Science",
  "Columbia University Vagelos College of Physicians and Surgeons",
  "Cooper Medical School of Rowan University",
  "Creighton University School of Medicine",
  "CUNY School of Medicine",
  "Dartmouth Geisel School of Medicine",
  "Donald and Barbara Zucker School of Medicine at Hofstra/Northwell",
  "Drexel University College of Medicine",
  "Duke University School of Medicine",
  "Eastern Virginia Medical School",
  "Emory University School of Medicine",
  "Florida Atlantic University Schmidt College of Medicine",
  "Florida International University Herbert Wertheim College of Medicine",
  "Florida State University College of Medicine",
  "Frank H. Netter MD School of Medicine at Quinnipiac University",
  "Geisinger Commonwealth School of Medicine",
  "George Washington University School of Medicine",
  "Georgetown University School of Medicine",
  "Harvard Medical School",
  "Howard University College of Medicine",
  "Icahn School of Medicine at Mount Sinai",
  "Indiana University School of Medicine",
  "Johns Hopkins University School of Medicine",
  "Kaiser Permanente Bernard J. Tyson School of Medicine",
  "Lewis Katz School of Medicine at Temple University",
  "Loma Linda University School of Medicine",
  "Louisiana State University School of Medicine in New Orleans",
  "Louisiana State University School of Medicine in Shreveport",
  "Loyola University Chicago Stritch School of Medicine",
  "Marshall University Joan C. Edwards School of Medicine",
  "Mayo Clinic Alix School of Medicine",
  "Medical College of Georgia at Augusta University",
  "Medical College of Wisconsin",
  "Medical University of South Carolina College of Medicine",
  "Meharry Medical College",
  "Michigan State University College of Human Medicine",
  "Morehouse School of Medicine",
  "New York Medical College",
  "NYU Grossman School of Medicine",
  "NYU Grossman Long Island School of Medicine",
  "Northeast Ohio Medical University",
  "Northwestern University Feinberg School of Medicine",
  "Nova Southeastern University Dr. Kiran C. Patel College of Allopathic Medicine",
  "Oakland University William Beaumont School of Medicine",
  "Ohio State University College of Medicine",
  "Oregon Health & Science University School of Medicine",
  "Penn State College of Medicine",
  "Perelman School of Medicine at the University of Pennsylvania",
  "Ponce Health Sciences University School of Medicine",
  "Renaissance School of Medicine at Stony Brook University",
  "Rosalind Franklin University Chicago Medical School",
  "Rush Medical College",
  "Rutgers New Jersey Medical School",
  "Rutgers Robert Wood Johnson Medical School",
  "Saint Louis University School of Medicine",
  "San Juan Bautista School of Medicine",
  "Sidney Kimmel Medical College at Thomas Jefferson University",
  "Southern Illinois University School of Medicine",
  "Stanford University School of Medicine",
  "SUNY Downstate Health Sciences University College of Medicine",
  "SUNY Upstate Medical University Norton College of Medicine",
  "TCU Burnett School of Medicine",
  "Texas A&M University School of Medicine",
  "Texas Tech University Health Sciences Center School of Medicine",
  "Texas Tech University Health Sciences Center El Paso Foster School of Medicine",
  "Tufts University School of Medicine",
  "Tulane University School of Medicine",
  "Uniformed Services University F. Edward Hébert School of Medicine",
  "University at Buffalo Jacobs School of Medicine",
  "University of Alabama at Birmingham Heersink School of Medicine",
  "University of Arizona College of Medicine - Phoenix",
  "University of Arizona College of Medicine - Tucson",
  "University of Arkansas for Medical Sciences College of Medicine",
  "University of California, Davis School of Medicine",
  "University of California, Irvine School of Medicine",
  "University of California, Los Angeles David Geffen School of Medicine",
  "University of California, Riverside School of Medicine",
  "University of California, San Diego School of Medicine",
  "University of California, San Francisco School of Medicine",
  "University of Central Florida College of Medicine",
  "University of Chicago Pritzker School of Medicine",
  "University of Cincinnati College of Medicine",
  "University of Colorado School of Medicine",
  "University of Connecticut School of Medicine",
  "University of Florida College of Medicine",
  "University of Hawaii John A. Burns School of Medicine",
  "University of Houston Tilman J. Fertitta Family College of Medicine",
  "University of Illinois College of Medicine",
  "University of Iowa Carver College of Medicine",
  "University of Kansas School of Medicine",
  "University of Kentucky College of Medicine",
  "University of Louisville School of Medicine",
  "University of Maryland School of Medicine",
  "University of Massachusetts T.H. Chan Medical School",
  "University of Miami Miller School of Medicine",
  "University of Michigan Medical School",
  "University of Minnesota Medical School",
  "University of Mississippi School of Medicine",
  "University of Missouri School of Medicine",
  "University of Missouri-Kansas City School of Medicine",
  "University of Nebraska College of Medicine",
  "University of Nevada, Las Vegas Kirk Kerkorian School of Medicine",
  "University of Nevada, Reno School of Medicine",
  "University of New Mexico School of Medicine",
  "University of North Carolina School of Medicine",
  "University of North Dakota School of Medicine and Health Sciences",
  "University of Oklahoma College of Medicine",
  "University of Pittsburgh School of Medicine",
  "University of Puerto Rico School of Medicine",
  "University of Rochester School of Medicine and Dentistry",
  "University of South Alabama Frederick P. Whiddon College of Medicine",
  "University of South Carolina School of Medicine Columbia",
  "University of South Carolina School of Medicine Greenville",
  "University of South Dakota Sanford School of Medicine",
  "University of South Florida Morsani College of Medicine",
  "University of Southern California Keck School of Medicine",
  "University of Tennessee Health Science Center College of Medicine",
  "University of Texas at Austin Dell Medical School",
  "University of Texas Medical Branch John Sealy School of Medicine",
  "University of Texas Rio Grande Valley School of Medicine",
  "University of Texas Southwestern Medical School",
  "University of Texas Health Science Center at Houston McGovern Medical School",
  "University of Texas Health Science Center at San Antonio Long School of Medicine",
  "University of Toledo College of Medicine and Life Sciences",
  "University of Utah Spencer Fox Eccles School of Medicine",
  "University of Vermont Larner College of Medicine",
  "University of Virginia School of Medicine",
  "University of Washington School of Medicine",
  "University of Wisconsin School of Medicine and Public Health",
  "Vanderbilt University School of Medicine",
  "Virginia Commonwealth University School of Medicine",
  "Virginia Tech Carilion School of Medicine",
  "Wake Forest University School of Medicine",
  "Washington State University Elson S. Floyd College of Medicine",
  "Washington University School of Medicine in St. Louis",
  "Wayne State University School of Medicine",
  "Weill Cornell Medicine",
  "West Virginia University School of Medicine",
  "Western Michigan University Homer Stryker M.D. School of Medicine",
  "Wright State University Boonshoft School of Medicine",
  "Yale School of Medicine",
];

export const DO_SCHOOLS = [
  "A.T. Still University Kirksville College of Osteopathic Medicine",
  "A.T. Still University School of Osteopathic Medicine in Arizona",
  "Alabama College of Osteopathic Medicine",
  "Arkansas College of Osteopathic Medicine",
  "Burrell College of Osteopathic Medicine",
  "Campbell University Jerry M. Wallace School of Osteopathic Medicine",
  "Des Moines University College of Osteopathic Medicine",
  "Edward Via College of Osteopathic Medicine",
  "Idaho College of Osteopathic Medicine",
  "Kansas City University College of Osteopathic Medicine",
  "Lake Erie College of Osteopathic Medicine",
  "Liberty University College of Osteopathic Medicine",
  "Lincoln Memorial University DeBusk College of Osteopathic Medicine",
  "Marian University College of Osteopathic Medicine",
  "Michigan State University College of Osteopathic Medicine",
  "Midwestern University Arizona College of Osteopathic Medicine",
  "Midwestern University Chicago College of Osteopathic Medicine",
  "New York Institute of Technology College of Osteopathic Medicine",
  "Noorda College of Osteopathic Medicine",
  "Nova Southeastern University Dr. Kiran C. Patel College of Osteopathic Medicine",
  "Ohio University Heritage College of Osteopathic Medicine",
  "Oklahoma State University College of Osteopathic Medicine",
  "Pacific Northwest University of Health Sciences College of Osteopathic Medicine",
  "Philadelphia College of Osteopathic Medicine",
  "Rocky Vista University College of Osteopathic Medicine",
  "Rowan-Virtua School of Osteopathic Medicine",
  "Sam Houston State University College of Osteopathic Medicine",
  "Touro College of Osteopathic Medicine",
  "Touro University California College of Osteopathic Medicine",
  "Touro University Nevada College of Osteopathic Medicine",
  "University of the Incarnate Word School of Osteopathic Medicine",
  "University of New England College of Osteopathic Medicine",
  "University of North Texas Health Science Center Texas College of Osteopathic Medicine",
  "University of Pikeville Kentucky College of Osteopathic Medicine",
  "West Virginia School of Osteopathic Medicine",
  "Western University of Health Sciences College of Osteopathic Medicine of the Pacific",
  "William Carey University College of Osteopathic Medicine",
];

export const MEDICAL_SCHOOLS: string[] = Array.from(new Set([...MD_SCHOOLS, ...DO_SCHOOLS])).sort((a, b) => a.localeCompare(b));

export const MEDICAL_SCHOOL_MAX = 120;

const squash = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

// Cleans a typed or picked school name. A name that matches a listed
// school (ignoring case and punctuation) is stored with the list's
// spelling, so the Insights filters group them together.
export function normalizeMedicalSchool(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const t = raw.replace(/\s+/g, " ").trim().slice(0, MEDICAL_SCHOOL_MAX);
  if (!t) return null;
  const key = squash(t);
  return MEDICAL_SCHOOLS.find((s) => squash(s) === key) ?? t;
}

// Best guess from what an applicant typed on the application form
// ("Johns Hopkins, MS3"): the listed school whose name contains every
// word they typed before the first comma, or their own text.
export function guessMedicalSchool(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const exact = normalizeMedicalSchool(raw);
  if (exact && MEDICAL_SCHOOLS.includes(exact)) return exact;
  const head = squash(raw.split(/[,(|/]/)[0] || "");
  const words = head.split(" ").filter((w) => w.length > 2 && !["school", "medicine", "university", "college", "the", "med"].includes(w));
  if (words.length) {
    const hits = MEDICAL_SCHOOLS.filter((s) => {
      const k = squash(s);
      return words.every((w) => k.includes(w));
    });
    if (hits.length === 1) return hits[0];
  }
  return exact;
}
